apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ems-frontend
  template:
    metadata:
      labels:
        app: ems-frontend
    spec:
      containers:
      - name: ems-frontend
        image: anjalidevu/ems-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ems-frontend
spec:
  selector:
    app: ems-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer